#!/usr/bin/env bash
# This script installs nginx

sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"

sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_404_config="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_404_config/" /etc/nginx/sites-enabled/default

sudo service nginx restart
