#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.

# Update the package manager cache
sudo apt-get -y update

# Install HAproxy
sudo apt-get -y install haproxy

# Edit config file
server_config=\
"
frontend  adepoju-frontend
        bind *:80
        mode http
        default_backend adepoju-backend
backend adepoju-backend
        balance roundrobin
        server 141861-web-01 107.22.142.218:80 check
        server 141861-web-02 54.83.163.157:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restart the haproxy load balancer after updating the settings
sudo service haproxy restart
