#!/usr/bin/env bash
# A Bash script that run the whoami command under the user passed

# Check if an argument is provided
if [ -z "$1" ]; then
  echo "Please provide a username as an argument."
  exit 1
fi

# Run `whoami` command under the specified user
sudo -u "$1" whoami
